# Settings
baseurl = "https://dainasouza.com.br/"
languageCode = "pt-br"
title = "Daina Souza Fotografia"
theme = "phugo"
googleAnalytics = "UA-47260469-1"
publishDir = "docs"

[params]

    # Meta
    description = "Daina Souza Fotografia - Galeria"
    author = "dainasouza"
    keywords = "photogallery, photoblog, daina, dainasouza, fotografia"
    
    # Headerbar links
    # Do not put here too many links,
    # it will break mobile appearance

    [[params.header.links]]
    name = "Sobre"
    url = "#footer"
    icon = "fa-info-circle"    
    
    # Footer panel
    
    [params.footer.paragraph]
    headline = "Daina Souza"
    text = "Olá! Eu sou analista de sistemas de dia e fotógrafa amadora nas horas vagas e esse site é uma pequena demonstração do meu trabalho. Vejo o mundo com as lentes de uma câmera procurando eternizar com fotos os momentos especiais."
    
    [params.footer.social]
    headline = "Siga me"

   
    [[params.footer.social.links]]
    label = "Facebook"
    url = "https://www.facebook.com/dainasouzafotografia/"
    icon = "fa-facebook"

    [[params.footer.social.links]]
    label = "Instagram"
    url = "https://instagram.com/daina_"
    icon = "fa-instagram"

    [[params.footer.social.links]]
    label = "flickr"
    url = "https://www.flickr.com/photos/daiphotos/"
    icon = "fa-flickr"

    [[params.footer.social.links]]
    label = "Pinterest"
    url = "https://br.pinterest.com/dainasouza/"
    icon = "fa-pinterest"

    
    # Contact form
    
    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'realEmail' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    
    [params.footer.contact]
    hide = false # Set this to true if you don't want to have a contact form on your site
    realEmail = "mailtodaina@gmail.com"
    headline = "Entre em contato"
    buttonText = "Enviar"
    resetText = "Limpar"
    
    # 'warning' defines error messages for invalid inputs
    [params.footer.contact.name]
    text = "Nome *"
    warning = "Insira aqui seu nome"

    [params.footer.contact.email]
    text = "Email *"
    warning = "Insira aqui seu email"

    [params.footer.contact.message]
    text = "Mensagem *"
    warning = "Digite aqui sua mensagem"
    
    # Copyright
    [params.footer.copyright]
    name = "Daina Souza Oenning"